//! Optional archive of included CSL styles.
// This file is generated by tests/generate.rs
// Do not edit by hand!

use citationberg::{Locale, Style};
use serde::de::DeserializeOwned;

/// A CSL style.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum StyleID {
    /// American Anthropological Association.
    ///
    /// Authors: Sebastian Karcher.
    AmericanAnthropologicalAssociation,
    /// Springer - Lecture Notes in Computer Science.
    ///
    /// Authors: Ammar Memari.
    SpringerLectureNotesInComputerScience,
    /// American Medical Association 11th edition.
    ///
    /// Authors: Julian Onions.
    AmericanMedicalAssociation,
    /// SAGE - Vancouver.
    ///
    /// Authors: Michael Berkowitz.
    SageVancouver,
    /// BioMed Central.
    ///
    /// Authors: Robert M Flight.
    BiomedCentral,
    /// American Society of Civil Engineers.
    ///
    /// Authors: Rintze Zelle.
    AmericanSocietyOfCivilEngineers,
    /// Taylor & Francis - Chicago Manual of Style (author-date).
    ///
    /// Authors: Sebastian Karcher.
    TaylorAndFrancisChicagoAuthorDate,
    /// China National Standard GB/T 7714-2015 (note, 中文).
    ///
    /// Authors: 牛耕田.
    Gb77142015Note,
    /// American Society for Microbiology.
    ///
    /// Authors: Julian Onions.
    AmericanSocietyForMicrobiology,
    /// American Meteorological Society.
    ///
    /// Authors: Carl J. Schreck, III.
    AmericanMeteorologicalSociety,
    /// Future Medicine journals.
    ///
    /// Authors: Patrick O'Bien.
    FutureMedicine,
    /// Bristol University Press.
    ///
    /// Authors: Patrick O'Brien.
    BristolUniversityPress,
    /// Public Library of Science.
    ///
    /// Authors: Sebastian Karcher.
    PublicLibraryOfScience,
    /// Pensoft Journals.
    ///
    /// Authors: Brian Stucky, Teodor Georgiev.
    Pensoft,
    /// American Institute of Aeronautics and Astronautics.
    ///
    /// Authors: Garrett Foster.
    AmericanInstituteOfAeronauticsAndAstronautics,
    /// Mary Ann Liebert - Vancouver.
    ///
    /// Authors: Patrick O'Brien.
    MaryAnnLiebertVancouver,
    /// Modern Humanities Research Association 3rd edition (note with bibliography).
    ///
    /// Authors: Rintze Zelle.
    ModernHumanitiesResearchAssociation,
    /// Springer - SocPsych (author-date).
    ///
    /// Authors: Charles Parnot.
    SpringerSocpsychAuthorDate,
    /// Trends journals.
    ///
    /// Authors: Adam Zeilinger.
    Trends,
    /// Russian GOST R 7.0.5-2008 (numeric).
    ///
    /// Authors: Yurkin Maxim.
    GostR7052008Numeric,
    /// American Political Science Association.
    ///
    /// Authors: Julian Onions.
    AmericanPoliticalScienceAssociation,
    /// Future Science Group.
    ///
    /// Authors: Sebastian Karcher.
    FutureScience,
    /// Association for Computing Machinery.
    ///
    /// Authors: Patrick O'Brien.
    AssociationForComputingMachinery,
    /// Elsevier - Harvard (with titles).
    ///
    /// Authors: David Kaplan.
    ElsevierHarvard,
    /// American Chemical Society.
    ///
    /// Authors: Julian Onions.
    AmericanChemicalSociety,
    /// Cell.
    ///
    /// Authors: Adam Mark.
    Cell,
    /// Royal Society of Chemistry.
    ///
    /// Authors: Julian Onions.
    RoyalSocietyOfChemistry,
    /// SIST02 (日本語).
    ///
    /// Authors: Shoji Takahashi.
    Sist02,
    /// China National Standard GB/T 7714-2005 (numeric, 中文).
    ///
    /// Authors: heromyth.
    Gb77142005Numeric,
    /// IEEE.
    ///
    /// Authors: Michael Berkowitz.
    InstituteOfElectricalAndElectronicsEngineers,
    /// Springer - Humanities (author-date).
    ///
    /// Authors: Sebastian Karcher.
    SpringerHumanitiesAuthorDate,
    /// Deutsche Gesellschaft für Psychologie 5. Auflage (Deutsch).
    ///
    /// Authors: Daniel Hirsbrunner.
    DeutscheGesellschaftFRPsychologie,
    /// Springer - Basic (author-date).
    ///
    /// Authors: Jens Allmer.
    SpringerBasicAuthorDate,
    /// Institute of Physics (numeric).
    ///
    /// Authors: Sebastian Karcher.
    InstituteOfPhysicsNumeric,
    /// Vancouver.
    ///
    /// Authors: Michael Berkowitz.
    Vancouver,
    /// Nature.
    ///
    /// Authors: Michael Berkowitz.
    Nature,
    /// Current Opinion journals.
    ///
    /// Authors: David M. Kaplan.
    CurrentOpinion,
    /// Annual Reviews (author-date).
    ///
    /// Authors: Michael Berkowitz.
    AnnualReviewsAuthorDate,
    /// American Institute of Physics 4th edition.
    ///
    /// Authors: Richard Karnesky.
    AmericanInstituteOfPhysics,
    /// China National Standard GB/T 7714-2015 (numeric, 中文).
    ///
    /// Authors: 牛耕田.
    Gb77142015Numeric,
    /// The Lancet.
    ///
    /// Authors: Sebastian Karcher.
    TheLancet,
    /// Springer - Basic (numeric, brackets).
    ///
    /// Authors: Charles Parnot.
    SpringerBasic,
    /// American Geophysical Union.
    ///
    /// Authors: Julian Onions, Simon Kornblith.
    AmericanGeophysicalUnion,
    /// Turabian 8th edition (full note).
    ///
    /// Authors: Elena Razlogova.
    TurabianFullnote8,
    /// Taylor & Francis - National Library of Medicine.
    ///
    /// Authors: Sebastian Karcher.
    TaylorAndFrancisNationalLibraryOfMedicine,
    /// American Physiological Society.
    ///
    /// Authors: Michael Berkowitz.
    AmericanPhysiologicalSociety,
    /// Thieme-German (Deutsch).
    ///
    /// Authors: Sebastian Karcher.
    Thieme,
    /// Copernicus Publications.
    ///
    /// Authors: Julian Onions.
    Copernicus,
    /// The Institution of Engineering and Technology.
    ///
    /// Authors: Sebastian Karcher.
    TheInstitutionOfEngineeringAndTechnology,
    /// Annual Reviews (sorted by order of appearance).
    ///
    /// Authors: Michael Berkowitz.
    AnnualReviews,
    /// Deutsche Sprache (Deutsch).
    ///
    /// Authors: Philipp Zumstein.
    DeutscheSprache,
    /// Cite Them Right 12th edition - Harvard.
    ///
    /// Authors: Patrick O'Brien.
    HarvardCiteThemRight,
    /// Chicago Manual of Style 17th edition (full note).
    ///
    /// Authors: Julian Onions.
    ChicagoFullnotes,
    /// ISO-690 (author-date, English).
    ///
    /// Authors: Laure Mellifluo, Raphael Grolimund, Michel Hardegger.
    Iso690AuthorDate,
    /// Council of Science Editors, Name-Year (author-date).
    ///
    /// Authors: Julian Onions.
    CouncilOfScienceEditorsAuthorDate,
    /// Springer - MathPhys (numeric, brackets).
    ///
    /// Authors: Charles Parnot.
    SpringerMathphys,
    /// American Society of Mechanical Engineers.
    ///
    /// Authors: Richard Karnesky.
    AmericanSocietyOfMechanicalEngineers,
    /// Karger journals.
    ///
    /// Authors: Sebastian Karcher.
    Karger,
    /// Multidisciplinary Digital Publishing Institute.
    ///
    /// Authors: Sebastian Karcher.
    MultidisciplinaryDigitalPublishingInstitute,
    /// American Psychological Association 7th edition.
    ///
    /// Authors: Brenton M. Wiernik.
    AmericanPsychologicalAssociation,
    /// Modern Language Association 8th edition.
    ///
    /// Authors: Sebastian Karcher.
    ModernLanguageAssociation8,
    /// China National Standard GB/T 7714-2015 (author-date, 中文).
    ///
    /// Authors: 牛耕田.
    Gb77142015AuthorDate,
    /// Springer - Vancouver (brackets).
    ///
    /// Authors: Charles Parnot.
    SpringerVancouver,
    /// BMJ.
    ///
    /// Authors: Sebastian Karcher.
    BritishMedicalJournal,
    /// Turabian 9th edition (author-date).
    ///
    /// Authors: Tony Chuang.
    TurabianAuthorDate,
    /// Chicago Manual of Style 17th edition (author-date).
    ///
    /// Authors: Julian Onions.
    ChicagoAuthorDate,
    /// Associação Brasileira de Normas Técnicas (Português - Brasil).
    ///
    /// Authors: Juliana Geyna Régis.
    AssociacaoBrasileiraDeNormasTecnicas,
    /// Vancouver (superscript).
    ///
    /// Authors: Michael Berkowitz.
    VancouverSuperscript,
    /// Angewandte Chemie International Edition.
    ///
    /// Authors: Richard Karnesky.
    AngewandteChemie,
    /// Elsevier (numeric, with titles).
    ///
    /// Authors: Richard Karnesky.
    ElsevierWithTitles,
    /// ISO-690 (numeric, English).
    ///
    /// Authors: Laure Mellifluo, Raphael Grolimund, Michel Hardegger.
    Iso690Numeric,
    /// Modern Language Association 9th edition.
    ///
    /// Authors: Sebastian Karcher.
    ModernLanguageAssociation,
    /// Council of Science Editors, Citation-Sequence (numeric, brackets).
    ///
    /// Authors: Pavel Giverts.
    CouncilOfScienceEditors,
    /// SPIE journals.
    ///
    /// Authors: Yurkin Maxim.
    Spie,
    /// Springer - Fachzeitschriften Medizin Psychologie (Deutsch).
    ///
    /// Authors: Philipp Zumstein.
    SpringerFachzeitschriftenMedizinPsychologie,
    /// Frontiers journals.
    ///
    /// Authors: Sebastian Karcher.
    Frontiers,
    /// American Physical Society.
    ///
    /// Authors: Richard Karnesky, Brenton M. Wiernik.
    AmericanPhysicsSociety,
    /// American Sociological Association 6th edition.
    ///
    /// Authors: Julian Onions.
    AmericanSociologicalAssociation,
    /// Elsevier - Vancouver.
    ///
    /// Authors: Richard Karnesky.
    ElsevierVancouver,
    /// Chicago Manual of Style 17th edition (note).
    ///
    /// Authors: Julian Onions.
    ChicagoNotes,
    /// Alphanumeric.
    ///
    /// Authors: Martin Haug, Laurenz Mädje.
    Alphanumeric,
}

impl StyleID {
    /// Retrieve this style.
    pub fn get(self) -> ArchivedStyle {
        match self {
            Self::AmericanAnthropologicalAssociation => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/american-anthropological-association.cbor"),
                id: "http://www.zotero.org/styles/american-anthropological-association",
                names: &[
                    "american-anthropological-association",
                ],
                full_name: "American Anthropological Association",
            },
            Self::SpringerLectureNotesInComputerScience => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/springer-lecture-notes-in-computer-science.cbor"),
                id: "http://www.zotero.org/styles/springer-lecture-notes-in-computer-science",
                names: &[
                    "springer-lecture-notes-in-computer-science",
                ],
                full_name: "Springer - Lecture Notes in Computer Science",
            },
            Self::AmericanMedicalAssociation => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/american-medical-association.cbor"),
                id: "http://www.zotero.org/styles/american-medical-association",
                names: &[
                    "american-medical-association",
                ],
                full_name: "American Medical Association 11th edition",
            },
            Self::SageVancouver => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/sage-vancouver.cbor"),
                id: "http://www.zotero.org/styles/sage-vancouver",
                names: &[
                    "sage-vancouver",
                ],
                full_name: "SAGE - Vancouver",
            },
            Self::BiomedCentral => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/biomed-central.cbor"),
                id: "http://www.zotero.org/styles/biomed-central",
                names: &[
                    "biomed-central",
                ],
                full_name: "BioMed Central",
            },
            Self::AmericanSocietyOfCivilEngineers => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/american-society-of-civil-engineers.cbor"),
                id: "http://www.zotero.org/styles/american-society-of-civil-engineers",
                names: &[
                    "american-society-of-civil-engineers",
                ],
                full_name: "American Society of Civil Engineers",
            },
            Self::TaylorAndFrancisChicagoAuthorDate => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/taylor-and-francis-chicago-author-date.cbor"),
                id: "http://www.zotero.org/styles/taylor-and-francis-chicago-author-date",
                names: &[
                    "taylor-and-francis-chicago-author-date",
                ],
                full_name: "Taylor & Francis - Chicago Manual of Style (author-date)",
            },
            Self::Gb77142015Note => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/china-national-standard-gb-t-7714-2015-note.cbor"),
                id: "http://www.zotero.org/styles/china-national-standard-gb-t-7714-2015-note",
                names: &[
                    "gb-7714-2015-note",
                ],
                full_name: "China National Standard GB/T 7714-2015 (note, 中文)",
            },
            Self::AmericanSocietyForMicrobiology => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/american-society-for-microbiology.cbor"),
                id: "http://www.zotero.org/styles/american-society-for-microbiology",
                names: &[
                    "american-society-for-microbiology",
                ],
                full_name: "American Society for Microbiology",
            },
            Self::AmericanMeteorologicalSociety => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/american-meteorological-society.cbor"),
                id: "http://www.zotero.org/styles/american-meteorological-society",
                names: &[
                    "american-meteorological-society",
                ],
                full_name: "American Meteorological Society",
            },
            Self::FutureMedicine => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/future-medicine.cbor"),
                id: "http://www.zotero.org/styles/future-medicine",
                names: &[
                    "future-medicine",
                ],
                full_name: "Future Medicine journals",
            },
            Self::BristolUniversityPress => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/bristol-university-press.cbor"),
                id: "http://www.zotero.org/styles/bristol-university-press",
                names: &[
                    "bristol-university-press",
                ],
                full_name: "Bristol University Press",
            },
            Self::PublicLibraryOfScience => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/plos.cbor"),
                id: "http://www.zotero.org/styles/plos",
                names: &[
                    "public-library-of-science",
                    "plos",
                ],
                full_name: "Public Library of Science",
            },
            Self::Pensoft => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/pensoft-journals.cbor"),
                id: "http://www.zotero.org/styles/pensoft-journals",
                names: &[
                    "pensoft",
                ],
                full_name: "Pensoft Journals",
            },
            Self::AmericanInstituteOfAeronauticsAndAstronautics => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/american-institute-of-aeronautics-and-astronautics.cbor"),
                id: "http://www.zotero.org/styles/american-institute-of-aeronautics-and-astronautics",
                names: &[
                    "american-institute-of-aeronautics-and-astronautics",
                ],
                full_name: "American Institute of Aeronautics and Astronautics",
            },
            Self::MaryAnnLiebertVancouver => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/mary-ann-liebert-vancouver.cbor"),
                id: "http://www.zotero.org/styles/mary-ann-liebert-vancouver",
                names: &[
                    "mary-ann-liebert-vancouver",
                ],
                full_name: "Mary Ann Liebert - Vancouver",
            },
            Self::ModernHumanitiesResearchAssociation => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/modern-humanities-research-association.cbor"),
                id: "http://www.zotero.org/styles/modern-humanities-research-association",
                names: &[
                    "modern-humanities-research-association",
                ],
                full_name: "Modern Humanities Research Association 3rd edition (note with bibliography)",
            },
            Self::SpringerSocpsychAuthorDate => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/springer-socpsych-author-date.cbor"),
                id: "http://www.zotero.org/styles/springer-socpsych-author-date",
                names: &[
                    "springer-socpsych-author-date",
                ],
                full_name: "Springer - SocPsych (author-date)",
            },
            Self::Trends => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/trends-journals.cbor"),
                id: "http://www.zotero.org/styles/trends-journals",
                names: &[
                    "trends",
                ],
                full_name: "Trends journals",
            },
            Self::GostR7052008Numeric => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/gost-r-7-0-5-2008-numeric.cbor"),
                id: "http://www.zotero.org/styles/gost-r-7-0-5-2008-numeric",
                names: &[
                    "gost-r-705-2008-numeric",
                ],
                full_name: "Russian GOST R 7.0.5-2008 (numeric)",
            },
            Self::AmericanPoliticalScienceAssociation => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/american-political-science-association.cbor"),
                id: "http://www.zotero.org/styles/american-political-science-association",
                names: &[
                    "american-political-science-association",
                ],
                full_name: "American Political Science Association",
            },
            Self::FutureScience => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/future-science-group.cbor"),
                id: "http://www.zotero.org/styles/future-science-group",
                names: &[
                    "future-science",
                ],
                full_name: "Future Science Group",
            },
            Self::AssociationForComputingMachinery => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/association-for-computing-machinery.cbor"),
                id: "http://www.zotero.org/styles/association-for-computing-machinery",
                names: &[
                    "association-for-computing-machinery",
                ],
                full_name: "Association for Computing Machinery",
            },
            Self::ElsevierHarvard => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/elsevier-harvard.cbor"),
                id: "http://www.zotero.org/styles/elsevier-harvard",
                names: &[
                    "elsevier-harvard",
                ],
                full_name: "Elsevier - Harvard (with titles)",
            },
            Self::AmericanChemicalSociety => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/american-chemical-society.cbor"),
                id: "http://www.zotero.org/styles/american-chemical-society",
                names: &[
                    "american-chemical-society",
                ],
                full_name: "American Chemical Society",
            },
            Self::Cell => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/cell.cbor"),
                id: "http://www.zotero.org/styles/cell",
                names: &[
                    "cell",
                ],
                full_name: "Cell",
            },
            Self::RoyalSocietyOfChemistry => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/royal-society-of-chemistry.cbor"),
                id: "http://www.zotero.org/styles/royal-society-of-chemistry",
                names: &[
                    "royal-society-of-chemistry",
                ],
                full_name: "Royal Society of Chemistry",
            },
            Self::Sist02 => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/sist02.cbor"),
                id: "http://www.zotero.org/styles/sist02",
                names: &[
                    "sist02",
                ],
                full_name: "SIST02 (日本語)",
            },
            Self::Gb77142005Numeric => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/chinese-gb7714-2005-numeric.cbor"),
                id: "http://www.zotero.org/styles/chinese-gb7714-2005-numeric",
                names: &[
                    "gb-7714-2005-numeric",
                ],
                full_name: "China National Standard GB/T 7714-2005 (numeric, 中文)",
            },
            Self::InstituteOfElectricalAndElectronicsEngineers => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/ieee.cbor"),
                id: "http://www.zotero.org/styles/ieee",
                names: &[
                    "institute-of-electrical-and-electronics-engineers",
                    "ieee",
                ],
                full_name: "IEEE",
            },
            Self::SpringerHumanitiesAuthorDate => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/springer-humanities-author-date.cbor"),
                id: "http://www.zotero.org/styles/springer-humanities-author-date",
                names: &[
                    "springer-humanities-author-date",
                ],
                full_name: "Springer - Humanities (author-date)",
            },
            Self::DeutscheGesellschaftFRPsychologie => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/deutsche-gesellschaft-fur-psychologie.cbor"),
                id: "http://www.zotero.org/styles/deutsche-gesellschaft-fur-psychologie",
                names: &[
                    "deutsche-gesellschaft-für-psychologie",
                ],
                full_name: "Deutsche Gesellschaft für Psychologie 5. Auflage (Deutsch)",
            },
            Self::SpringerBasicAuthorDate => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/springer-basic-author-date.cbor"),
                id: "http://www.zotero.org/styles/springer-basic-author-date",
                names: &[
                    "springer-basic-author-date",
                ],
                full_name: "Springer - Basic (author-date)",
            },
            Self::InstituteOfPhysicsNumeric => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/institute-of-physics-numeric.cbor"),
                id: "http://www.zotero.org/styles/institute-of-physics-numeric",
                names: &[
                    "institute-of-physics-numeric",
                ],
                full_name: "Institute of Physics (numeric)",
            },
            Self::Vancouver => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/vancouver.cbor"),
                id: "http://www.zotero.org/styles/vancouver",
                names: &[
                    "vancouver",
                ],
                full_name: "Vancouver",
            },
            Self::Nature => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/nature.cbor"),
                id: "http://www.zotero.org/styles/nature",
                names: &[
                    "nature",
                ],
                full_name: "Nature",
            },
            Self::CurrentOpinion => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/current-opinion.cbor"),
                id: "http://www.zotero.org/styles/current-opinion",
                names: &[
                    "current-opinion",
                ],
                full_name: "Current Opinion journals",
            },
            Self::AnnualReviewsAuthorDate => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/annual-reviews-author-date.cbor"),
                id: "http://www.zotero.org/styles/annual-reviews-author-date",
                names: &[
                    "annual-reviews-author-date",
                ],
                full_name: "Annual Reviews (author-date)",
            },
            Self::AmericanInstituteOfPhysics => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/american-institute-of-physics.cbor"),
                id: "http://www.zotero.org/styles/american-institute-of-physics",
                names: &[
                    "american-institute-of-physics",
                ],
                full_name: "American Institute of Physics 4th edition",
            },
            Self::Gb77142015Numeric => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/china-national-standard-gb-t-7714-2015-numeric.cbor"),
                id: "http://www.zotero.org/styles/china-national-standard-gb-t-7714-2015-numeric",
                names: &[
                    "gb-7714-2015-numeric",
                ],
                full_name: "China National Standard GB/T 7714-2015 (numeric, 中文)",
            },
            Self::TheLancet => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/the-lancet.cbor"),
                id: "http://www.zotero.org/styles/the-lancet",
                names: &[
                    "the-lancet",
                ],
                full_name: "The Lancet",
            },
            Self::SpringerBasic => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/springer-basic-brackets.cbor"),
                id: "http://www.zotero.org/styles/springer-basic-brackets",
                names: &[
                    "springer-basic",
                ],
                full_name: "Springer - Basic (numeric, brackets)",
            },
            Self::AmericanGeophysicalUnion => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/american-geophysical-union.cbor"),
                id: "http://www.zotero.org/styles/american-geophysical-union",
                names: &[
                    "american-geophysical-union",
                ],
                full_name: "American Geophysical Union",
            },
            Self::TurabianFullnote8 => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/turabian-fullnote-bibliography-8th-edition.cbor"),
                id: "http://www.zotero.org/styles/turabian-fullnote-bibliography-8th-edition",
                names: &[
                    "turabian-fullnote-8",
                ],
                full_name: "Turabian 8th edition (full note)",
            },
            Self::TaylorAndFrancisNationalLibraryOfMedicine => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/taylor-and-francis-national-library-of-medicine.cbor"),
                id: "http://www.zotero.org/styles/taylor-and-francis-national-library-of-medicine",
                names: &[
                    "taylor-and-francis-national-library-of-medicine",
                ],
                full_name: "Taylor & Francis - National Library of Medicine",
            },
            Self::AmericanPhysiologicalSociety => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/american-physiological-society.cbor"),
                id: "http://www.zotero.org/styles/american-physiological-society",
                names: &[
                    "american-physiological-society",
                ],
                full_name: "American Physiological Society",
            },
            Self::Thieme => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/thieme-german.cbor"),
                id: "http://www.zotero.org/styles/thieme-german",
                names: &[
                    "thieme",
                ],
                full_name: "Thieme-German (Deutsch)",
            },
            Self::Copernicus => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/copernicus-publications.cbor"),
                id: "http://www.zotero.org/styles/copernicus-publications",
                names: &[
                    "copernicus",
                ],
                full_name: "Copernicus Publications",
            },
            Self::TheInstitutionOfEngineeringAndTechnology => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/the-institution-of-engineering-and-technology.cbor"),
                id: "http://www.zotero.org/styles/the-institution-of-engineering-and-technology",
                names: &[
                    "the-institution-of-engineering-and-technology",
                ],
                full_name: "The Institution of Engineering and Technology",
            },
            Self::AnnualReviews => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/annual-reviews.cbor"),
                id: "http://www.zotero.org/styles/annual-reviews",
                names: &[
                    "annual-reviews",
                ],
                full_name: "Annual Reviews (sorted by order of appearance)",
            },
            Self::DeutscheSprache => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/deutsche-sprache.cbor"),
                id: "http://www.zotero.org/styles/deutsche-sprache",
                names: &[
                    "deutsche-sprache",
                ],
                full_name: "Deutsche Sprache (Deutsch)",
            },
            Self::HarvardCiteThemRight => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/harvard-cite-them-right.cbor"),
                id: "http://www.zotero.org/styles/harvard-cite-them-right",
                names: &[
                    "harvard-cite-them-right",
                ],
                full_name: "Cite Them Right 12th edition - Harvard",
            },
            Self::ChicagoFullnotes => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/chicago-fullnote-bibliography.cbor"),
                id: "http://www.zotero.org/styles/chicago-fullnote-bibliography",
                names: &[
                    "chicago-fullnotes",
                ],
                full_name: "Chicago Manual of Style 17th edition (full note)",
            },
            Self::Iso690AuthorDate => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/iso690-author-date-en.cbor"),
                id: "http://www.zotero.org/styles/iso690-author-date-en",
                names: &[
                    "iso-690-author-date",
                ],
                full_name: "ISO-690 (author-date, English)",
            },
            Self::CouncilOfScienceEditorsAuthorDate => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/council-of-science-editors-author-date.cbor"),
                id: "http://www.zotero.org/styles/council-of-science-editors-author-date",
                names: &[
                    "council-of-science-editors-author-date",
                ],
                full_name: "Council of Science Editors, Name-Year (author-date)",
            },
            Self::SpringerMathphys => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/springer-mathphys-brackets.cbor"),
                id: "http://www.zotero.org/styles/springer-mathphys-brackets",
                names: &[
                    "springer-mathphys",
                ],
                full_name: "Springer - MathPhys (numeric, brackets)",
            },
            Self::AmericanSocietyOfMechanicalEngineers => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/american-society-of-mechanical-engineers.cbor"),
                id: "http://www.zotero.org/styles/american-society-of-mechanical-engineers",
                names: &[
                    "american-society-of-mechanical-engineers",
                ],
                full_name: "American Society of Mechanical Engineers",
            },
            Self::Karger => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/karger-journals.cbor"),
                id: "http://www.zotero.org/styles/karger-journals",
                names: &[
                    "karger",
                ],
                full_name: "Karger journals",
            },
            Self::MultidisciplinaryDigitalPublishingInstitute => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/multidisciplinary-digital-publishing-institute.cbor"),
                id: "http://www.zotero.org/styles/multidisciplinary-digital-publishing-institute",
                names: &[
                    "multidisciplinary-digital-publishing-institute",
                ],
                full_name: "Multidisciplinary Digital Publishing Institute",
            },
            Self::AmericanPsychologicalAssociation => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/apa.cbor"),
                id: "http://www.zotero.org/styles/apa",
                names: &[
                    "american-psychological-association",
                    "apa",
                ],
                full_name: "American Psychological Association 7th edition",
            },
            Self::ModernLanguageAssociation8 => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/modern-language-association-8th-edition.cbor"),
                id: "http://www.zotero.org/styles/modern-language-association-8th-edition",
                names: &[
                    "modern-language-association-8",
                    "mla-8",
                ],
                full_name: "Modern Language Association 8th edition",
            },
            Self::Gb77142015AuthorDate => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/china-national-standard-gb-t-7714-2015-author-date.cbor"),
                id: "http://www.zotero.org/styles/china-national-standard-gb-t-7714-2015-author-date",
                names: &[
                    "gb-7714-2015-author-date",
                ],
                full_name: "China National Standard GB/T 7714-2015 (author-date, 中文)",
            },
            Self::SpringerVancouver => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/springer-vancouver-brackets.cbor"),
                id: "http://www.zotero.org/styles/springer-vancouver-brackets",
                names: &[
                    "springer-vancouver",
                ],
                full_name: "Springer - Vancouver (brackets)",
            },
            Self::BritishMedicalJournal => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/bmj.cbor"),
                id: "http://www.zotero.org/styles/bmj",
                names: &[
                    "british-medical-journal",
                    "bmj",
                ],
                full_name: "BMJ",
            },
            Self::TurabianAuthorDate => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/turabian-author-date.cbor"),
                id: "http://www.zotero.org/styles/turabian-author-date",
                names: &[
                    "turabian-author-date",
                ],
                full_name: "Turabian 9th edition (author-date)",
            },
            Self::ChicagoAuthorDate => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/chicago-author-date.cbor"),
                id: "http://www.zotero.org/styles/chicago-author-date",
                names: &[
                    "chicago-author-date",
                ],
                full_name: "Chicago Manual of Style 17th edition (author-date)",
            },
            Self::AssociacaoBrasileiraDeNormasTecnicas => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/associacao-brasileira-de-normas-tecnicas.cbor"),
                id: "http://www.zotero.org/styles/associacao-brasileira-de-normas-tecnicas",
                names: &[
                    "associacao-brasileira-de-normas-tecnicas",
                ],
                full_name: "Associação Brasileira de Normas Técnicas (Português - Brasil)",
            },
            Self::VancouverSuperscript => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/vancouver-superscript.cbor"),
                id: "http://www.zotero.org/styles/vancouver-superscript",
                names: &[
                    "vancouver-superscript",
                ],
                full_name: "Vancouver (superscript)",
            },
            Self::AngewandteChemie => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/angewandte-chemie.cbor"),
                id: "http://www.zotero.org/styles/angewandte-chemie",
                names: &[
                    "angewandte-chemie",
                ],
                full_name: "Angewandte Chemie International Edition",
            },
            Self::ElsevierWithTitles => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/elsevier-with-titles.cbor"),
                id: "http://www.zotero.org/styles/elsevier-with-titles",
                names: &[
                    "elsevier-with-titles",
                ],
                full_name: "Elsevier (numeric, with titles)",
            },
            Self::Iso690Numeric => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/iso690-numeric-en.cbor"),
                id: "http://www.zotero.org/styles/iso690-numeric-en",
                names: &[
                    "iso-690-numeric",
                ],
                full_name: "ISO-690 (numeric, English)",
            },
            Self::ModernLanguageAssociation => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/modern-language-association.cbor"),
                id: "http://www.zotero.org/styles/modern-language-association",
                names: &[
                    "modern-language-association",
                    "mla",
                ],
                full_name: "Modern Language Association 9th edition",
            },
            Self::CouncilOfScienceEditors => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/council-of-science-editors-brackets.cbor"),
                id: "http://www.zotero.org/styles/council-of-science-editors-brackets",
                names: &[
                    "council-of-science-editors",
                ],
                full_name: "Council of Science Editors, Citation-Sequence (numeric, brackets)",
            },
            Self::Spie => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/spie-journals.cbor"),
                id: "http://www.zotero.org/styles/spie-journals",
                names: &[
                    "spie",
                ],
                full_name: "SPIE journals",
            },
            Self::SpringerFachzeitschriftenMedizinPsychologie => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/springer-fachzeitschriften-medizin-psychologie.cbor"),
                id: "http://www.zotero.org/styles/springer-fachzeitschriften-medizin-psychologie",
                names: &[
                    "springer-fachzeitschriften-medizin-psychologie",
                ],
                full_name: "Springer - Fachzeitschriften Medizin Psychologie (Deutsch)",
            },
            Self::Frontiers => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/frontiers.cbor"),
                id: "http://www.zotero.org/styles/frontiers",
                names: &[
                    "frontiers",
                ],
                full_name: "Frontiers journals",
            },
            Self::AmericanPhysicsSociety => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/american-physics-society.cbor"),
                id: "http://www.zotero.org/styles/american-physics-society",
                names: &[
                    "american-physics-society",
                ],
                full_name: "American Physical Society",
            },
            Self::AmericanSociologicalAssociation => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/american-sociological-association.cbor"),
                id: "http://www.zotero.org/styles/american-sociological-association",
                names: &[
                    "american-sociological-association",
                ],
                full_name: "American Sociological Association 6th edition",
            },
            Self::ElsevierVancouver => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/elsevier-vancouver.cbor"),
                id: "http://www.zotero.org/styles/elsevier-vancouver",
                names: &[
                    "elsevier-vancouver",
                ],
                full_name: "Elsevier - Vancouver",
            },
            Self::ChicagoNotes => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/chicago-note-bibliography.cbor"),
                id: "http://www.zotero.org/styles/chicago-note-bibliography",
                names: &[
                    "chicago-notes",
                ],
                full_name: "Chicago Manual of Style 17th edition (note)",
            },
            Self::Alphanumeric => ArchivedStyle {
                bytes: include_bytes!("../../archive/styles/alphanumeric.cbor"),
                id: "http://typst.org/csl/alphanumeric",
                names: &[
                    "alphanumeric",
                ],
                full_name: "Alphanumeric",
            },
        }
    }

    /// Retrieve all available style IDs.
    pub fn all() -> &'static [Self] {
        &[
            Self::AmericanAnthropologicalAssociation,
            Self::SpringerLectureNotesInComputerScience,
            Self::AmericanMedicalAssociation,
            Self::SageVancouver,
            Self::BiomedCentral,
            Self::AmericanSocietyOfCivilEngineers,
            Self::TaylorAndFrancisChicagoAuthorDate,
            Self::Gb77142015Note,
            Self::AmericanSocietyForMicrobiology,
            Self::AmericanMeteorologicalSociety,
            Self::FutureMedicine,
            Self::BristolUniversityPress,
            Self::PublicLibraryOfScience,
            Self::Pensoft,
            Self::AmericanInstituteOfAeronauticsAndAstronautics,
            Self::MaryAnnLiebertVancouver,
            Self::ModernHumanitiesResearchAssociation,
            Self::SpringerSocpsychAuthorDate,
            Self::Trends,
            Self::GostR7052008Numeric,
            Self::AmericanPoliticalScienceAssociation,
            Self::FutureScience,
            Self::AssociationForComputingMachinery,
            Self::ElsevierHarvard,
            Self::AmericanChemicalSociety,
            Self::Cell,
            Self::RoyalSocietyOfChemistry,
            Self::Sist02,
            Self::Gb77142005Numeric,
            Self::InstituteOfElectricalAndElectronicsEngineers,
            Self::SpringerHumanitiesAuthorDate,
            Self::DeutscheGesellschaftFRPsychologie,
            Self::SpringerBasicAuthorDate,
            Self::InstituteOfPhysicsNumeric,
            Self::Vancouver,
            Self::Nature,
            Self::CurrentOpinion,
            Self::AnnualReviewsAuthorDate,
            Self::AmericanInstituteOfPhysics,
            Self::Gb77142015Numeric,
            Self::TheLancet,
            Self::SpringerBasic,
            Self::AmericanGeophysicalUnion,
            Self::TurabianFullnote8,
            Self::TaylorAndFrancisNationalLibraryOfMedicine,
            Self::AmericanPhysiologicalSociety,
            Self::Thieme,
            Self::Copernicus,
            Self::TheInstitutionOfEngineeringAndTechnology,
            Self::AnnualReviews,
            Self::DeutscheSprache,
            Self::HarvardCiteThemRight,
            Self::ChicagoFullnotes,
            Self::Iso690AuthorDate,
            Self::CouncilOfScienceEditorsAuthorDate,
            Self::SpringerMathphys,
            Self::AmericanSocietyOfMechanicalEngineers,
            Self::Karger,
            Self::MultidisciplinaryDigitalPublishingInstitute,
            Self::AmericanPsychologicalAssociation,
            Self::ModernLanguageAssociation8,
            Self::Gb77142015AuthorDate,
            Self::SpringerVancouver,
            Self::BritishMedicalJournal,
            Self::TurabianAuthorDate,
            Self::ChicagoAuthorDate,
            Self::AssociacaoBrasileiraDeNormasTecnicas,
            Self::VancouverSuperscript,
            Self::AngewandteChemie,
            Self::ElsevierWithTitles,
            Self::Iso690Numeric,
            Self::ModernLanguageAssociation,
            Self::CouncilOfScienceEditors,
            Self::Spie,
            Self::SpringerFachzeitschriftenMedizinPsychologie,
            Self::Frontiers,
            Self::AmericanPhysicsSociety,
            Self::AmericanSociologicalAssociation,
            Self::ElsevierVancouver,
            Self::ChicagoNotes,
            Self::Alphanumeric,
        ]
    }

    /// Retrieve this style by name.
    pub fn by_name(name: &str) -> Option<Self> {
        match name {
            "american-anthropological-association" => Some(Self::AmericanAnthropologicalAssociation),
            "springer-lecture-notes-in-computer-science" => Some(Self::SpringerLectureNotesInComputerScience),
            "american-medical-association" => Some(Self::AmericanMedicalAssociation),
            "sage-vancouver" => Some(Self::SageVancouver),
            "biomed-central" => Some(Self::BiomedCentral),
            "american-society-of-civil-engineers" => Some(Self::AmericanSocietyOfCivilEngineers),
            "taylor-and-francis-chicago-author-date" => Some(Self::TaylorAndFrancisChicagoAuthorDate),
            "gb-7714-2015-note" => Some(Self::Gb77142015Note),
            "american-society-for-microbiology" => Some(Self::AmericanSocietyForMicrobiology),
            "american-meteorological-society" => Some(Self::AmericanMeteorologicalSociety),
            "future-medicine" => Some(Self::FutureMedicine),
            "bristol-university-press" => Some(Self::BristolUniversityPress),
            "public-library-of-science" => Some(Self::PublicLibraryOfScience),
            "plos" => Some(Self::PublicLibraryOfScience),
            "pensoft" => Some(Self::Pensoft),
            "american-institute-of-aeronautics-and-astronautics" => Some(Self::AmericanInstituteOfAeronauticsAndAstronautics),
            "mary-ann-liebert-vancouver" => Some(Self::MaryAnnLiebertVancouver),
            "modern-humanities-research-association" => Some(Self::ModernHumanitiesResearchAssociation),
            "springer-socpsych-author-date" => Some(Self::SpringerSocpsychAuthorDate),
            "trends" => Some(Self::Trends),
            "gost-r-705-2008-numeric" => Some(Self::GostR7052008Numeric),
            "american-political-science-association" => Some(Self::AmericanPoliticalScienceAssociation),
            "future-science" => Some(Self::FutureScience),
            "association-for-computing-machinery" => Some(Self::AssociationForComputingMachinery),
            "elsevier-harvard" => Some(Self::ElsevierHarvard),
            "american-chemical-society" => Some(Self::AmericanChemicalSociety),
            "cell" => Some(Self::Cell),
            "royal-society-of-chemistry" => Some(Self::RoyalSocietyOfChemistry),
            "sist02" => Some(Self::Sist02),
            "gb-7714-2005-numeric" => Some(Self::Gb77142005Numeric),
            "institute-of-electrical-and-electronics-engineers" => Some(Self::InstituteOfElectricalAndElectronicsEngineers),
            "ieee" => Some(Self::InstituteOfElectricalAndElectronicsEngineers),
            "springer-humanities-author-date" => Some(Self::SpringerHumanitiesAuthorDate),
            "deutsche-gesellschaft-für-psychologie" => Some(Self::DeutscheGesellschaftFRPsychologie),
            "springer-basic-author-date" => Some(Self::SpringerBasicAuthorDate),
            "institute-of-physics-numeric" => Some(Self::InstituteOfPhysicsNumeric),
            "vancouver" => Some(Self::Vancouver),
            "nature" => Some(Self::Nature),
            "current-opinion" => Some(Self::CurrentOpinion),
            "annual-reviews-author-date" => Some(Self::AnnualReviewsAuthorDate),
            "american-institute-of-physics" => Some(Self::AmericanInstituteOfPhysics),
            "gb-7714-2015-numeric" => Some(Self::Gb77142015Numeric),
            "the-lancet" => Some(Self::TheLancet),
            "springer-basic" => Some(Self::SpringerBasic),
            "american-geophysical-union" => Some(Self::AmericanGeophysicalUnion),
            "turabian-fullnote-8" => Some(Self::TurabianFullnote8),
            "taylor-and-francis-national-library-of-medicine" => Some(Self::TaylorAndFrancisNationalLibraryOfMedicine),
            "american-physiological-society" => Some(Self::AmericanPhysiologicalSociety),
            "thieme" => Some(Self::Thieme),
            "copernicus" => Some(Self::Copernicus),
            "the-institution-of-engineering-and-technology" => Some(Self::TheInstitutionOfEngineeringAndTechnology),
            "annual-reviews" => Some(Self::AnnualReviews),
            "deutsche-sprache" => Some(Self::DeutscheSprache),
            "harvard-cite-them-right" => Some(Self::HarvardCiteThemRight),
            "chicago-fullnotes" => Some(Self::ChicagoFullnotes),
            "iso-690-author-date" => Some(Self::Iso690AuthorDate),
            "council-of-science-editors-author-date" => Some(Self::CouncilOfScienceEditorsAuthorDate),
            "springer-mathphys" => Some(Self::SpringerMathphys),
            "american-society-of-mechanical-engineers" => Some(Self::AmericanSocietyOfMechanicalEngineers),
            "karger" => Some(Self::Karger),
            "multidisciplinary-digital-publishing-institute" => Some(Self::MultidisciplinaryDigitalPublishingInstitute),
            "american-psychological-association" => Some(Self::AmericanPsychologicalAssociation),
            "apa" => Some(Self::AmericanPsychologicalAssociation),
            "modern-language-association-8" => Some(Self::ModernLanguageAssociation8),
            "mla-8" => Some(Self::ModernLanguageAssociation8),
            "gb-7714-2015-author-date" => Some(Self::Gb77142015AuthorDate),
            "springer-vancouver" => Some(Self::SpringerVancouver),
            "british-medical-journal" => Some(Self::BritishMedicalJournal),
            "bmj" => Some(Self::BritishMedicalJournal),
            "turabian-author-date" => Some(Self::TurabianAuthorDate),
            "chicago-author-date" => Some(Self::ChicagoAuthorDate),
            "associacao-brasileira-de-normas-tecnicas" => Some(Self::AssociacaoBrasileiraDeNormasTecnicas),
            "vancouver-superscript" => Some(Self::VancouverSuperscript),
            "angewandte-chemie" => Some(Self::AngewandteChemie),
            "elsevier-with-titles" => Some(Self::ElsevierWithTitles),
            "iso-690-numeric" => Some(Self::Iso690Numeric),
            "modern-language-association" => Some(Self::ModernLanguageAssociation),
            "mla" => Some(Self::ModernLanguageAssociation),
            "council-of-science-editors" => Some(Self::CouncilOfScienceEditors),
            "spie" => Some(Self::Spie),
            "springer-fachzeitschriften-medizin-psychologie" => Some(Self::SpringerFachzeitschriftenMedizinPsychologie),
            "frontiers" => Some(Self::Frontiers),
            "american-physics-society" => Some(Self::AmericanPhysicsSociety),
            "american-sociological-association" => Some(Self::AmericanSociologicalAssociation),
            "elsevier-vancouver" => Some(Self::ElsevierVancouver),
            "chicago-notes" => Some(Self::ChicagoNotes),
            "alphanumeric" => Some(Self::Alphanumeric),
            _ => None
        }
    }

    /// Retrieve this style by CSL ID.
    pub fn by_id(id: &str) -> Option<Self> {
        match id {
            "http://www.zotero.org/styles/american-anthropological-association" => Some(Self::AmericanAnthropologicalAssociation),
            "http://www.zotero.org/styles/springer-lecture-notes-in-computer-science" => Some(Self::SpringerLectureNotesInComputerScience),
            "http://www.zotero.org/styles/american-medical-association" => Some(Self::AmericanMedicalAssociation),
            "http://www.zotero.org/styles/sage-vancouver" => Some(Self::SageVancouver),
            "http://www.zotero.org/styles/biomed-central" => Some(Self::BiomedCentral),
            "http://www.zotero.org/styles/american-society-of-civil-engineers" => Some(Self::AmericanSocietyOfCivilEngineers),
            "http://www.zotero.org/styles/taylor-and-francis-chicago-author-date" => Some(Self::TaylorAndFrancisChicagoAuthorDate),
            "http://www.zotero.org/styles/china-national-standard-gb-t-7714-2015-note" => Some(Self::Gb77142015Note),
            "http://www.zotero.org/styles/american-society-for-microbiology" => Some(Self::AmericanSocietyForMicrobiology),
            "http://www.zotero.org/styles/american-meteorological-society" => Some(Self::AmericanMeteorologicalSociety),
            "http://www.zotero.org/styles/future-medicine" => Some(Self::FutureMedicine),
            "http://www.zotero.org/styles/bristol-university-press" => Some(Self::BristolUniversityPress),
            "http://www.zotero.org/styles/plos" => Some(Self::PublicLibraryOfScience),
            "http://www.zotero.org/styles/pensoft-journals" => Some(Self::Pensoft),
            "http://www.zotero.org/styles/american-institute-of-aeronautics-and-astronautics" => Some(Self::AmericanInstituteOfAeronauticsAndAstronautics),
            "http://www.zotero.org/styles/mary-ann-liebert-vancouver" => Some(Self::MaryAnnLiebertVancouver),
            "http://www.zotero.org/styles/modern-humanities-research-association" => Some(Self::ModernHumanitiesResearchAssociation),
            "http://www.zotero.org/styles/springer-socpsych-author-date" => Some(Self::SpringerSocpsychAuthorDate),
            "http://www.zotero.org/styles/trends-journals" => Some(Self::Trends),
            "http://www.zotero.org/styles/gost-r-7-0-5-2008-numeric" => Some(Self::GostR7052008Numeric),
            "http://www.zotero.org/styles/american-political-science-association" => Some(Self::AmericanPoliticalScienceAssociation),
            "http://www.zotero.org/styles/future-science-group" => Some(Self::FutureScience),
            "http://www.zotero.org/styles/association-for-computing-machinery" => Some(Self::AssociationForComputingMachinery),
            "http://www.zotero.org/styles/elsevier-harvard" => Some(Self::ElsevierHarvard),
            "http://www.zotero.org/styles/american-chemical-society" => Some(Self::AmericanChemicalSociety),
            "http://www.zotero.org/styles/cell" => Some(Self::Cell),
            "http://www.zotero.org/styles/royal-society-of-chemistry" => Some(Self::RoyalSocietyOfChemistry),
            "http://www.zotero.org/styles/sist02" => Some(Self::Sist02),
            "http://www.zotero.org/styles/chinese-gb7714-2005-numeric" => Some(Self::Gb77142005Numeric),
            "http://www.zotero.org/styles/ieee" => Some(Self::InstituteOfElectricalAndElectronicsEngineers),
            "http://www.zotero.org/styles/springer-humanities-author-date" => Some(Self::SpringerHumanitiesAuthorDate),
            "http://www.zotero.org/styles/deutsche-gesellschaft-fur-psychologie" => Some(Self::DeutscheGesellschaftFRPsychologie),
            "http://www.zotero.org/styles/springer-basic-author-date" => Some(Self::SpringerBasicAuthorDate),
            "http://www.zotero.org/styles/institute-of-physics-numeric" => Some(Self::InstituteOfPhysicsNumeric),
            "http://www.zotero.org/styles/vancouver" => Some(Self::Vancouver),
            "http://www.zotero.org/styles/nature" => Some(Self::Nature),
            "http://www.zotero.org/styles/current-opinion" => Some(Self::CurrentOpinion),
            "http://www.zotero.org/styles/annual-reviews-author-date" => Some(Self::AnnualReviewsAuthorDate),
            "http://www.zotero.org/styles/american-institute-of-physics" => Some(Self::AmericanInstituteOfPhysics),
            "http://www.zotero.org/styles/china-national-standard-gb-t-7714-2015-numeric" => Some(Self::Gb77142015Numeric),
            "http://www.zotero.org/styles/the-lancet" => Some(Self::TheLancet),
            "http://www.zotero.org/styles/springer-basic-brackets" => Some(Self::SpringerBasic),
            "http://www.zotero.org/styles/american-geophysical-union" => Some(Self::AmericanGeophysicalUnion),
            "http://www.zotero.org/styles/turabian-fullnote-bibliography-8th-edition" => Some(Self::TurabianFullnote8),
            "http://www.zotero.org/styles/taylor-and-francis-national-library-of-medicine" => Some(Self::TaylorAndFrancisNationalLibraryOfMedicine),
            "http://www.zotero.org/styles/american-physiological-society" => Some(Self::AmericanPhysiologicalSociety),
            "http://www.zotero.org/styles/thieme-german" => Some(Self::Thieme),
            "http://www.zotero.org/styles/copernicus-publications" => Some(Self::Copernicus),
            "http://www.zotero.org/styles/the-institution-of-engineering-and-technology" => Some(Self::TheInstitutionOfEngineeringAndTechnology),
            "http://www.zotero.org/styles/annual-reviews" => Some(Self::AnnualReviews),
            "http://www.zotero.org/styles/deutsche-sprache" => Some(Self::DeutscheSprache),
            "http://www.zotero.org/styles/harvard-cite-them-right" => Some(Self::HarvardCiteThemRight),
            "http://www.zotero.org/styles/chicago-fullnote-bibliography" => Some(Self::ChicagoFullnotes),
            "http://www.zotero.org/styles/iso690-author-date-en" => Some(Self::Iso690AuthorDate),
            "http://www.zotero.org/styles/council-of-science-editors-author-date" => Some(Self::CouncilOfScienceEditorsAuthorDate),
            "http://www.zotero.org/styles/springer-mathphys-brackets" => Some(Self::SpringerMathphys),
            "http://www.zotero.org/styles/american-society-of-mechanical-engineers" => Some(Self::AmericanSocietyOfMechanicalEngineers),
            "http://www.zotero.org/styles/karger-journals" => Some(Self::Karger),
            "http://www.zotero.org/styles/multidisciplinary-digital-publishing-institute" => Some(Self::MultidisciplinaryDigitalPublishingInstitute),
            "http://www.zotero.org/styles/apa" => Some(Self::AmericanPsychologicalAssociation),
            "http://www.zotero.org/styles/modern-language-association-8th-edition" => Some(Self::ModernLanguageAssociation8),
            "http://www.zotero.org/styles/china-national-standard-gb-t-7714-2015-author-date" => Some(Self::Gb77142015AuthorDate),
            "http://www.zotero.org/styles/springer-vancouver-brackets" => Some(Self::SpringerVancouver),
            "http://www.zotero.org/styles/bmj" => Some(Self::BritishMedicalJournal),
            "http://www.zotero.org/styles/turabian-author-date" => Some(Self::TurabianAuthorDate),
            "http://www.zotero.org/styles/chicago-author-date" => Some(Self::ChicagoAuthorDate),
            "http://www.zotero.org/styles/associacao-brasileira-de-normas-tecnicas" => Some(Self::AssociacaoBrasileiraDeNormasTecnicas),
            "http://www.zotero.org/styles/vancouver-superscript" => Some(Self::VancouverSuperscript),
            "http://www.zotero.org/styles/angewandte-chemie" => Some(Self::AngewandteChemie),
            "http://www.zotero.org/styles/elsevier-with-titles" => Some(Self::ElsevierWithTitles),
            "http://www.zotero.org/styles/iso690-numeric-en" => Some(Self::Iso690Numeric),
            "http://www.zotero.org/styles/modern-language-association" => Some(Self::ModernLanguageAssociation),
            "http://www.zotero.org/styles/council-of-science-editors-brackets" => Some(Self::CouncilOfScienceEditors),
            "http://www.zotero.org/styles/spie-journals" => Some(Self::Spie),
            "http://www.zotero.org/styles/springer-fachzeitschriften-medizin-psychologie" => Some(Self::SpringerFachzeitschriftenMedizinPsychologie),
            "http://www.zotero.org/styles/frontiers" => Some(Self::Frontiers),
            "http://www.zotero.org/styles/american-physics-society" => Some(Self::AmericanPhysicsSociety),
            "http://www.zotero.org/styles/american-sociological-association" => Some(Self::AmericanSociologicalAssociation),
            "http://www.zotero.org/styles/elsevier-vancouver" => Some(Self::ElsevierVancouver),
            "http://www.zotero.org/styles/chicago-note-bibliography" => Some(Self::ChicagoNotes),
            "http://typst.org/csl/alphanumeric" => Some(Self::Alphanumeric),
            _ => None
        }
    }
}

/// An archived CSL style.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ArchivedStyle {
    /// The archived bytes.
    bytes: &'static [u8],
    /// The ID of the style.
    pub id: &'static str,
    /// The name of the style in Hayagriva.
    /// The first name is the canonical one.
    pub names: &'static [&'static str],
    /// The full CSL name of the style.
    pub full_name: &'static str,
}

impl ArchivedStyle {
    /// Retrieve this style.
    pub fn style(&self) -> Style {
        from_cbor::<Style>(self.bytes).unwrap()
    }
}

fn from_cbor<T: DeserializeOwned>(
    reader: &[u8],
) -> Result<T, ciborium::de::Error<std::io::Error>> {
    ciborium::de::from_reader(reader)
}

/// CBOR-encoded CSL locales.
pub const LOCALES: &[&[u8]] = &[
    include_bytes!("../../archive/locales/is-IS.cbor"),
    include_bytes!("../../archive/locales/km-KH.cbor"),
    include_bytes!("../../archive/locales/bg-BG.cbor"),
    include_bytes!("../../archive/locales/pt-PT.cbor"),
    include_bytes!("../../archive/locales/ru-RU.cbor"),
    include_bytes!("../../archive/locales/tr-TR.cbor"),
    include_bytes!("../../archive/locales/et-EE.cbor"),
    include_bytes!("../../archive/locales/da-DK.cbor"),
    include_bytes!("../../archive/locales/de-AT.cbor"),
    include_bytes!("../../archive/locales/gl-ES.cbor"),
    include_bytes!("../../archive/locales/fr-CA.cbor"),
    include_bytes!("../../archive/locales/de-CH.cbor"),
    include_bytes!("../../archive/locales/pt-BR.cbor"),
    include_bytes!("../../archive/locales/sl-SI.cbor"),
    include_bytes!("../../archive/locales/es-CL.cbor"),
    include_bytes!("../../archive/locales/eu.cbor"),
    include_bytes!("../../archive/locales/hu-HU.cbor"),
    include_bytes!("../../archive/locales/mn-MN.cbor"),
    include_bytes!("../../archive/locales/uk-UA.cbor"),
    include_bytes!("../../archive/locales/ca-AD.cbor"),
    include_bytes!("../../archive/locales/lv-LV.cbor"),
    include_bytes!("../../archive/locales/fi-FI.cbor"),
    include_bytes!("../../archive/locales/hr-HR.cbor"),
    include_bytes!("../../archive/locales/zh-CN.cbor"),
    include_bytes!("../../archive/locales/id-ID.cbor"),
    include_bytes!("../../archive/locales/es-MX.cbor"),
    include_bytes!("../../archive/locales/en-US.cbor"),
    include_bytes!("../../archive/locales/sv-SE.cbor"),
    include_bytes!("../../archive/locales/lt-LT.cbor"),
    include_bytes!("../../archive/locales/zh-TW.cbor"),
    include_bytes!("../../archive/locales/sk-SK.cbor"),
    include_bytes!("../../archive/locales/ko-KR.cbor"),
    include_bytes!("../../archive/locales/he-IL.cbor"),
    include_bytes!("../../archive/locales/de-DE.cbor"),
    include_bytes!("../../archive/locales/cs-CZ.cbor"),
    include_bytes!("../../archive/locales/fr-FR.cbor"),
    include_bytes!("../../archive/locales/la.cbor"),
    include_bytes!("../../archive/locales/nn-NO.cbor"),
    include_bytes!("../../archive/locales/nb-NO.cbor"),
    include_bytes!("../../archive/locales/ar.cbor"),
    include_bytes!("../../archive/locales/hi-IN.cbor"),
    include_bytes!("../../archive/locales/af-ZA.cbor"),
    include_bytes!("../../archive/locales/fa-IR.cbor"),
    include_bytes!("../../archive/locales/ja-JP.cbor"),
    include_bytes!("../../archive/locales/vi-VN.cbor"),
    include_bytes!("../../archive/locales/ro-RO.cbor"),
    include_bytes!("../../archive/locales/cy-GB.cbor"),
    include_bytes!("../../archive/locales/it-IT.cbor"),
    include_bytes!("../../archive/locales/en-GB.cbor"),
    include_bytes!("../../archive/locales/pl-PL.cbor"),
    include_bytes!("../../archive/locales/sr-RS.cbor"),
    include_bytes!("../../archive/locales/nl-NL.cbor"),
    include_bytes!("../../archive/locales/el-GR.cbor"),
    include_bytes!("../../archive/locales/th-TH.cbor"),
    include_bytes!("../../archive/locales/es-ES.cbor"),
];

/// Get all CSL locales.
pub fn locales() -> Vec<Locale> {
    LOCALES.iter().map(|bytes| {
        from_cbor::<Locale>(bytes).unwrap()
    }).collect()
}
