[workspace]
members = ["crates/*", "tests"]
resolver = "2"

[workspace.package]
version = "0.10.1"
authors = [
  "Martin Haug <mhaug@live.de>",
  "Daniel Drodt <daniel.drodt@tu-darmstadt.de>",
]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/typst/hayagriva"
readme = "README.md"
keywords = ["hayagriva", "bibliography", "citation", "reference", "literature"]

[workspace.dependencies]
biblatex = { version = "0.12.0", features = ["unic-langid"] }
ciborium = { version = "0.2.1" }
citationberg = "0.7.0"
indexmap = { version = "2.0.2", features = ["serde"] }
hayagriva-archive = { path = "crates/hayagriva-archive" }
hayagriva-cli = { path = "crates/hayagriva-cli" }
hayagriva-core = { path = "crates/hayagriva-core" }
hayagriva-csl = { path = "crates/hayagriva-csl" }
hayagriva-csl-json = { path = "crates/hayagriva-csl-json" }
hayagriva-format = { path = "crates/hayagriva-format" }
serde = { version = "1", features = ["derive"] }
thiserror = "2.0.16"
unic-langid = { version = "0.9.6", features = ["serde"] }
unicode-segmentation = "1.6.0"
unscanny = "0.1.0"
url = { version = "2.4", features = ["serde"] }
