[workspace]
members = [
  "crates/hayagriva-archive",
  "crates/hayagriva-biblatex",
  "crates/hayagriva-cli",
  "crates/hayagriva-core",
  "crates/hayagriva-csl",
  "crates/hayagriva-format",
  "crates/hayagriva-json",
  "crates/tests",
]
resolver = "2"

[workspace.package]
version = "0.10.1"
authors = [
  "Martin Haug <mhaug@live.de>",
  "Daniel Drodt <daniel.drodt@tu-darmstadt.de>",
]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/typst/hayagriva"
readme = "README.md"
keywords = ["bibliography", "citation", "reference", "literature"]

[workspace.dependencies]
biblatex = { version = "0.12.0", features = ["unic-langid"] }
ciborium = { version = "0.2.1" }
citationberg = "0.7.0"
indexmap = { version = "2.0.2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
unic-langid = { version = "0.9.6", features = ["serde"] }
unicode-segmentation = "1.6.0"
thiserror = "2.0.16"
unscanny = "0.1.0"
url = { version = "2.4", features = ["serde"] }
