[package]
name = "hayagriva-archive"
description = "Archived CSL styles and locales for Hayagriva/Typst."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords = [
  "hayagriva",
  "bibliography",
  "citation",
  "reference",
  "literature",
  "archive",
  "citation style language",
  "locales",
]

[dependencies]
ciborium = { workspace = true }
citationberg = { workspace = true }
serde = { workspace = true }
