[package]
name = "hayagriva-archive"
description = "Archived CSL styles and locales for Hayagriva/Typst"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true

[dependencies]
citationberg = { workspace = true }
serde = { workspace = true }
hayagriva-core = { path = "../hayagriva-core" }
ciborium = { workspace = true }

[dev-dependencies]
heck = "0.5"
