[package]
name = "hayagriva-csl"
description = "Citation Style Language procesor and renderer for Hayagriva."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords = [
  "hayagriva",
  "bibliography",
  "citation",
  "reference",
  "literature",
  "rendering",
]

[dependencies]
citationberg = { workspace = true }
indexmap = { workspace = true }
icu_collator = "2.2.0"
icu_locale = "2.2.0"
hayagriva-core = { workspace = true }
unic-langid = { workspace = true }

[dev-dependencies]
hayagriva-format = { workspace = true }
