[package]
name = "hayagriva-core"
description = "Core data types and utilities for Hayagriva."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords = ["hayagriva", "bibliography", "citation", "reference", "literature"]

[dependencies]
serde = { workspace = true }
url = { workspace = true }
thiserror = { workspace = true }
citationberg = { workspace = true }
unscanny = { workspace = true }
roman-numerals-rs = "3.1.0"
unicode-segmentation = { workspace = true }
