[package]
name = "hayagriva-json"
description = "Archived CSL styles and locales for Hayagriva/Typst"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true

[dependencies]
citationberg = { workspace = true, features = ["json"] }
hayagriva-core = { path = "../hayagriva-core" }
serde = { workspace = true, features = ["derive"] }
